spring:
  application:
    name: kdy

  # Database Setting
  dataSource:
    H2:
      url: ${{ secrets.DATASOURCE_URL_H2 }}
      username: ${{ secrets.DATASOURCE_USERNAME_H2 }}
      password: ${{ secrets.DATASOURCE_PASSWORD_H2 }}
      driver-class-name: org.h2.Driver

    MariaDB:
      url: ${{ secrets.DATASOURCE_URL_MARIADB }}
      username: ${{ secrets.DATASOURCE_USERNAME_MARIADB }}
      password: ${{ secrets.DATASOURCE_PASSWORD_MARIADB }}
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # ddl-auto: none # Application이 재실행 돼도 테이블 유지
      ddl-auto: create # Application이 재실행 될 때마다 테이블 Drop + Create

    properties:
      hibernate:
        show-sql: true # Hibernate SQL을 Console에 출력
        format-sql: true # Hibernate가 생성하는 SQL을 가독성 좋게 표현

# 데이터 베이스 실행 시, SQL 확인을 위한 설정 (Hibernate)
logging:
  level:
    org.hibernate.SQL: info
