spring:
  application:
    name: kdy

  # Database Setting
  datasource:
    h2:
      url: ${SPRING_DATASOURCE_H2_URL}
      username: ${SPRING_DATASOURCE_H2_USERNAME}
      password: ${SPRING_DATASOURCE_H2_PASSWORD}
      driver-class-name: org.h2.Driver

    mariadb:
      jdbc-url: ${SPRING_DATASOURCE_MARIADB_URL}
      username: ${SPRING_DATASOURCE_MARIADB_USERNAME}
      password: ${SPRING_DATASOURCE_MARIADB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # ddl-auto: none # Application이 재실행 돼도 테이블 유지
      ddl-auto: create # Application이 재실행 될 때마다 테이블 Drop + Create

    properties:
      hibernate:
        show-sql: true # Hibernate SQL을 Console에 출력
        format-sql: true # Hibernate가 생성하는 SQL을 가독성 좋게 표현

# 데이터 베이스 실행 시, SQL 확인을 위한 설정 (Hibernate)
logging:
  level:
    org.hibernate.SQL: info
