name: GitHub Actions CD With Naver Cloud
on:
  workflow_run:
    workflows: [GitHub Actions CI With Docker Build]
    types: [completed] # 상단의 Workflow가 실행 완료 됐을 경우에만 실행

jobs:
  deploy:
    # 빌드 성공 시 실행 (GitHub 정해진 문법)
    # on.workflow_run.workflows.types는 실패도 포함, 성공일 경우에만 실행
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Step01 : SSH 개인 Key 세팅 (NCP 서버 접속용)
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.NCP_SSH_PRIVATE_KEY }}

      # Step02 : NCP 서버에서 Docker 이미지 Pull 및 Container 재시작
      - name: Deploy latest Docker image on NCP server
        run:
          |
          ssh -o StrictHostKeyChecking=no ${{ secrets.NCP_SSH_USER }}@${{ secrets.NCP_SERVER_IP }} << 'EOF'
          echo "Pull latest image from Docker Hub"
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          
          echo "Stop existing container if running"
          docker stop ${{ secrets.DOCKER_REPOSITORY }} || true
          docker rm ${{ secrets.DOCKER_REPOSITORY }} || true
          
          echo "Run new container with environment variables"
          docker run -d --name ${{ secrets.DOCKER_REPOSITORY }} -p 80:8080 \
          -e SPRING_DATASOURCE_MARIADB_URL=${{ secrets.SPRING_DATASOURCE_MARIADB_URL }} \
          -e SPRING_DATASOURCE_MARIADB_USERNAME=${{ secrets.SPRING_DATASOURCE_MARIADB_USERNAME }} \
          -e SPRING_DATASOURCE_MARIADB_PASSWORD=${{ secrets.SPRING_DATASOURCE_MARIADB_PASSWORD }} \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          
          echo "Deployment completed successfully"
          EOF