name: CI And Docker Build Image

on:
  push:
    branches: [main] # 메인 Branch에 Push가 발생할 경우 실행

  pull_request:
    branches: [main] # # 메인 Branch에 PR이 발생할 경우 실행

jobs:
  build:
    runs-on: ubuntu-latest # GitHub 가상 환경 : Ubuntu 최신 환경

    permissions: # # Job 실행 시 필요한 권한
      contents: read # Repository Contents를 읽을 수 있는 권한

    steps:
    # Step01 : GitHub Repository 코드 Check Out
    - uses: actions/checkout@v4

    # Step02 : 실행 권한 부여 = 안 줄 경우 권한 오류 발생 (= Process completed with exit code 126)
    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew

    # Step03 : Java 17 Install
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # 사용할 JDK 배포판

    # Step04 : Gradle 캐싱 설정
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # Step05 : Gradle Build 실행 (Test 포함)
    - name: Build with Gradle
      run: ./gradlew build

    # Step06 : Upload Jar (GitHub Action Artifact)
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: kdy-build
        path: build/libs/kdy-0.0.1-SNAPSHOT.jar

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step01 : GitHub Repository 코드 Check Out
      - uses: actions/checkout@v4

      # Step02 : Jar File Download > Job이 분리되어 있어서 다운로드 해야 위치를 찾음
      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: kdy-build
          path: build/libs

      # Step03 : Setting Docker Buildx ( 멀티 플랫폼 빌드나 고급 빌드를 위해 사용)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step04 : DockerHub Login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step05 : Build 시킨 후 이미지로 만들기
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: darong95/toypractice:latest