name: Docker Build Process

on:
  workflow_run:
    workflows: [GitHub Actions CI Pipelines]
    types: [completed] # 상단의 Workflow가 실행 완료 됐을 경우에만 실행

jobs:
  build:
    runs-on: ubuntu-latest # GitHub 가상 환경 : Ubuntu 최신 환경

    steps:
    # Step01 : GitHub Repository 코드 Check Out
    - uses: actions/checkout@v4

    # Step02 : Setting Docker Buildx ( 멀티 플랫폼 빌드나 고급 빌드를 위해 사용)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step03 : DockerHub Login
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step04 : Build 시킨 후 이미지로 만들기
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: darong95/toypractice:latest